image: gradle:latest

stages:
    - test-stage
    - build-stage

test-job:
    stage: test-stage
    script:
        - gradle check

build-job:
    stage: build-stage
    script:
        - gradle build
        - gradle jacocoTestCoverageVerification


        

